# Generated by Django 2.1.2 on 2018-10-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongID', models.CharField(max_length=40, verbose_name='SongID')),
                ('Domain', models.CharField(max_length=40, verbose_name='Domain')),
                ('AlbumName', models.CharField(max_length=40, verbose_name='AlbumName')),
                ('SingerName', models.CharField(max_length=40, verbose_name='SingerName')),
                ('SongName', models.CharField(max_length=40, verbose_name='SongName')),
                ('SongPath', models.CharField(max_length=100, verbose_name='SongPath')),
                ('AlbumImgPath', models.CharField(max_length=100, verbose_name='AlbumImgPath')),
                ('Lyrics', models.TextField(max_length=2000, verbose_name='Lyrics')),
            ],
        ),
    ]
