# Generated by Django 2.1.2 on 2018-10-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='ori_url',
        ),
    ]
