# Generated by Django 2.1.2 on 2018-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_img_ori_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='png_filename',
            field=models.CharField(default='', max_length=40, verbose_name='png_filename'),
        ),
    ]
